apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ferretdb-db
  namespace: ferretdb
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  imageName: ghcr.io/ferretdb/postgres-documentdb:17-0.107.0-ferretdb-2.7.0
  postgresUID: 999
  postgresGID: 999
  enableSuperuserAccess: true
  storage:
    size: 10Gi
    storageClass: local-path
  postgresql:
    shared_preload_libraries:
      - pg_cron
      - pg_documentdb_core
      - pg_documentdb
    parameters:
      cron.database_name: "postgres"
  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS documentdb CASCADE;
