apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ebloved-db
  namespace: ebloved
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
