---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ebloved-env
  namespace: ebloved
spec:
  encryptedData:
    SECRET_KEY_BASE: AgBRgGlP//5yj+LQaveNcNtGiUU/2VuU1fQcozE6gv1m0odzRAbK9CDqaVMF5PuzWEsVXbDPPtOUqvv4p7aQ1YsFywY8sTnfb3dmwhLFbeYvqM6jToofB0aqBarI80b976dh6VU8eagfbo7bb/d9AJmUOmL3ViT8mta09tT20XNZuWKHZMtMVCOyUwOhFVQqZgUhz5TQL2UBRXJd1dpRl7nvU1mI9jhpIag2wCkTfJ5mErWTmoKsEsCKM4ZXoG4MpisT10zeq6PAwxXHKZRQiXmt9pza9l7tuf0+bBh0e1WvGXhC9Ox8YylQ2KTj+0zm3XKxo9ztElvS7e/IwuB6aRPO2cKbvFKjlxH1cyatB6gludxoTfY4MylXiCcKZyHSKsBT7sc+gkoKrwn/A4CtoaBNnTcqGglGtSlm8j17hT3K1oyV/8PKZtPF27VhAPWnLtBQ10hAq7TLERhizGMdg6UdhXs4ibpiv5hHYMyXG+EbzQnZsNdBviqoO9sEN4LIBVU3Ig64xRlJ5WDU9CeWz3sfYcvXsYOo5a3QSY9u1/fC8Oa8DxcfrTSqVZ/9U2CcuGSGB36RjjCGVajUtkng/dzd6+5811ES2GJADIReuIhpAO4Pk2TT/j579ZsYiRLA7vAnxhcv4H9nh35QsnRbgsZ8ScN3z14KiysyigV+06C8DPqQpcuzj65oWb5pkHNGtzEjCuw4DbpEBoS5mhEH/kfuuziRSXxsqRFMBnu3elKGf6aa02+0xQ/oArIM7jk33YpcwfY2pHSMMo7qx/qD2NKE
  template:
    metadata:
      name: ebloved-env
      namespace: ebloved
