apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lonk-data
  namespace: lonk
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
